### PR TITLE
Issue-7 | Updates for the issue "Set up database for project"

### PR DESCRIPTION
**Pull request by iScous**
Completed: created a volume for a database. Updated dockerfile and docker-compose file. Now the image on the droplet is building from the docker-compose.yml file that is storing in the folder myDocker. To build a new image we should use the command:

```sh
docker-compose up -d
```

The full documentation is in the description for the issue.
Issue: #7

### CODE REVIEW

**Comment by iScous** [comment]
@arsenykonohovwork ready for review

**Comment by arsenykonohovwork** [comment]
@iScous
- You had to indicate path to yaml config as: `/myDocker/docker-compose.yml`;
- Is it ok place thins not in user space `~` but in root `/` of droplet?
- You have to describe all operations we have to perform in order to test this issue is done, for me it's not clear, i will not investigate things while you update process step by step in description;

Please make things predictable;

**Comment by arsenykonohovwork** [comment]
screen shot 2018-10-13 at 16 57 06

**Comment by iScous** [comment]
@arsenykonohovwork ready for review.

**Pull request merged**
