### PR TITLE
Set up database for project

### PR DESCRIPTION
**Pull request by iScous**
Completed: README.md file was created with the instructions and steps i followed to complete that issue
Issue: #7

### CODE REVIEW

**Comment by iScous** [comment]
@arsenykonohovwork ready for review

**Comment by arsenykonohovwork** [comment]
@iScous please follow latest comments in this issue:
https://github.com/arsenykonohovwork/inspectah-curvaceous/pull/14

**Comment by iScous** [comment]
@arsenykonohovwork i think i've already fixed what you asked me to do in this comments

**Comment by arsenykonohovwork** [comment]
@iScous 
I suppose you have to create file in our secure space (shared GDRIVE) for saving credentials and similar secure info;

**Pull request merged**
