### PR TITLE
Application concept schema

### PR DESCRIPTION
**Pull request by iScous**
Completed: Created a schema and some documentation
Issue: #11

### CODE REVIEW

**Comment by iScous** [comment]
@arsenykonohovwork made some changes in the schema, attached an image with it. also [this is a link](https://drive.google.com/file/d/1Z3mfoFStzTAwpvZCu-acaPOXFp4gQbK8/view?usp=sharing) to the google drive where you can find it and edit

**Comment by arsenykonohovwork** [comment]
@iScous please attach all resources to the related issue (description).
What kind of image do you mean?

**Comment by arsenykonohovwork** [comment]
@iScous please follow latest comments in issue:
https://github.com/arsenykonohovwork/inspectah-curvaceous/pull/14

**Comment by iScous** [comment]
@arsenykonohovwork i mean Application concept.png file.  Attached it to the description of the issue #11

**Comment by iScous** [comment]
@arsenykonohovwork documentation for #11 issue was added

**Pull request merged**
