### PR TITLE
Created documentation for a cookie/token-based authentication

### PR DESCRIPTION
**Pull request by iScous**
Completed: Created documentation for a cookie/token-based authentication
Issue: #10

### CODE REVIEW

**Comment by iScous** [comment]
@arsenykonohovwork ready for review

**Comment by arsenykonohovwork** [comment]
@iScous  you have to create schema for token-based authentication;

**Comment by iScous** [comment]
@arsenykonohovwork added a schema into the description of the issue #10

**Comment by arsenykonohovwork** [comment]
@iScous please resolve conflict and make merge to default branch;

**Pull request merged**
